#!/bin/bash

# Copied from https://github.com/basecamp/omarchy/blob/dev/bin/omarchy-launch-or-focus-tui

# Launch or focus on a given TUI identified by the passed in as the command.
# Use by commands like omarchy-launch-wifi to ensure there is only one wifi configuration screen open.

APP_ID="org.omarchy.$(basename "$1")"
LAUNCH_COMMAND="open-tui $@"

exec open-or-focus "$APP_ID" "$LAUNCH_COMMAND"
