# Extra autostart processes
# exec-once = uwsm app -- my-service

exec-once = hyprctl dispatch workspace 1
exec-once = alacritty
exec-once = chromium "https://learn.omacom.io/2/the-omarchy-manual/53/hotkeys"
