# Make sure all script helpers are in PATH
env = PATH,<PATH-TO-HOME>/.config/scripts/hypr-helpers:$PATH

# Add cargo bin (bluetooth, audio) into the mix
env = PATH,<PATH-TO-HOME>/.cargo/bin:$PATH

# Add gobin (wifitui) into the mix
env = PATH,<PATH-TO-HOME>/go/bin:$PATH

# Set terminal to alacritty
env = TERMINAL,alacritty

# make sure screenshots go to ~/Pictures/Screenshots
env = HYPRSHOT_DIR,<PATH-TO-HOME>/Pictures/Screenshots
