# Extra env variables
# Note: You must relaunch Hyprland after changing envs (use Super+Esc, then Relaunch)
# env = MY_GLOBAL_ENV,setting

# Add cargo bin (bluetooth, audio) into the mix
env = PATH,/home/mdeaguiargomes/.cargo/bin:$PATH
# Add gobin (wifitui) into the mix
env = PATH,/home/mdeaguiargomes/go/bin:$PATH

# Set terminal to alacritty
env = TERMINAL,alacritty

# make sure screenshots go to ~/Pictures/Screenshots
env = HYPRSHOT_DIR,/home/mdeaguiargomes/Pictures/Screenshots
