windowrule = match:class Alacritty, opacity 0.97 0.9
windowrule = match:class org.omarchy.wiremix, float on, size 900 600, opacity 0.85 0.75
windowrule = match:class org.omarchy.bluetui, float on, size 900 600, opacity 0.85 0.75
windowrule = match:class org.omarchy.wifitui, float on, size 550 600, opacity 0.85 0.75
windowrule = match:class org.omarchy.btop, float on, size 900 600, opacity 0.85 0.75
windowrule = match:class org.omarchy.calcure, float on, size 900 600, opacity 0.85 0.75
windowrule = match:class org.gnome.Nautilus, float on, size 900 600, opacity 0.97 0.90
windowrule = match:class xdg-desktop-portal-gtk, float on, size 900 600, opacity 0.97 0.90


# xdg-desktop-portal-hyprland share picker
windowrule = float on, match:class hyprland-share-picker
# windowrule = match:class hyprland-share-picker, stay_focused on
windowrule = pin on, match:class hyprland-share-picker
